#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MySMSWebChat.Resource", IsApplication=true)]

namespace MySMSWebChat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int fourthColor = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int primaryColor = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int primaryDarkColor = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int primaryLightColor = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int primaryTextColor = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int secondaryColor = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int secondaryDarkColor = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int secondaryLightColor = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int secondaryTextColor = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int thirdColor = 2130968584;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_applauncher2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_notification_sms5 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_support7 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_user7 = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int buttonOK = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int buttonSend = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int editTextMsg = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int listViewMsgs = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int space1 = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int textView1 = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int textView2 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MySMSWebChat = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReceivedMessageItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SentMessageItem = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom1 = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
